spectator:
  applicationName: $${spring.application.name}
  webEndpoint:
    enabled: false

# sql:
#   enabled: true
#   connectionPool:
#     jdbcUrl: jdbc:mysql://$${services.mysql.host}/orca
#     user: orca
#     password: $${secrets.mysql_password.orca}
#     connectionTimeout: 5000
#     maxLifetime: 30000
#     # MariaDB-specific:
#     maxPoolSize: 50
#   migration:
#     jdbcUrl: jdbc:mysql://$${services.mysql.host}/orca
#     user: orca
#     password: $${secrets.mysql_password.orca}

# Ensure we're only using SQL for accessing execution state
# executionRepository:
#   sql:
#     enabled: true
#   redis:
#     enabled: false

# Reporting on active execution metrics will be handled by SQL
# monitor:
#   activeExecutions:
#     redis: false

# Use SQL for Orca's work queue
# Settings from Netflix and may require adjustment for your environment
# Only validated with AWS Aurora MySQL 5.7
# Please PR if you have success with other databases
# keiko:
#   queue:
#     sql:
#       enabled: true
#     redis:
#       enabled: false

queue:
  zombieCheck:
    enabled: true
  # pendingExecutionService:
  #   sql:
  #     enabled: true
  #   redis:
  #     enabled: false

server:
  port: $${services.orca.port:8083}
  address: $${services.orca.host:localhost}

tasks:
  executionWindow:
    timezone: $${global.spinnaker.timezone:America/Los_Angeles}
  daysOfExecutionHistory: 365

webhook:
  trust:
    enabled: false

integrations:
  gremlin:
    enabled: false
    baseUrl: https://api.gremlin.com/v1

pipelineTemplates.enabled: true
pipelineTemplate.enabled: true
plugins: {}

teamcity:
  deckUrl: https://${deck_host}
  profiles:
    - name: aw
      serverURL: https://teamcity.aw.cloud.yandex.net
      tokenFile: /secrets/teamcity/aw_token
