# https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
serviceAccount:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: ${service_account_iam_role_arn}
